Devportal certificates feature
wso2/apim-apps pull request #307
Opened 2022-08-02 07:25 UTC by prasa7

2022-08-02 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/apim-apps?pullRequest=307) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wso2/apim-apps?pullRequest=307) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: prasa7<br/>:x: Abirame-ship-it<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/apim-apps?pullRequest=307) it.</sub>

2022-08-02 08:56 UTC, tmkasun requested changes

2022-08-02 08:56 UTC, tmkasun commented on portals/devportal/source/src/app/components/Applications/Details/Certificates.jsx
> +import React, { useEffect, useState } from 'react';
@chanaka3d  Shall we please migrate Developer portal to Typescript as well ??

2022-09-06 06:56 UTC, chanaka3d commented
Since this feature is no longer in need, I am closing the PR

2022-09-06 06:56 UTC, closed without merging