[Main] Adding new test cases for API Publisher
wso2/apim-apps pull request #491
Opened 2023-08-20 08:06 UTC by vishmi49

2023-08-20 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/apim-apps?pullRequest=491) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/apim-apps?pullRequest=491) before we can accept your contribution.<br/><hr/>**vishmi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/apim-apps?pullRequest=491) it.</sub>

2023-08-23 09:37 UTC, dulithsenanayake requested changes

2023-08-23 09:37 UTC, dulithsenanayake commented on tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
> +  const deployeandPublish = (apiId) => {
Typo

2023-08-23 09:37 UTC, dulithsenanayake commented on tests/cypress/integration/publisher/002-api-resources/02-add-assign-global-scopes-for-api.spec.js
> +
Remove unnecessary empty lines. Check others

2023-08-23 09:37 UTC, dulithsenanayake commented on tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
> +});
Shall we add EOF here? Check others

2023-08-24 04:13 UTC, vishmi49 commented on tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
> +});
Resolved in the latest commit

2023-08-26 00:48 UTC, dulithsenanayake approved these changes

2023-08-26 08:56 UTC, merged