Add cypress tests for Gateway-Policy feature UI
wso2/apim-apps pull request #526
Opened 2024-01-08 04:57 UTC by YasasRangika

### Purpose
To enhance the quality and reliability of the Gateway Policy feature by introducing UI tests. These UI tests are designed to validate the functionality, user interactions, and edge cases within the Gateway Policy feature's user interface

### Goal
Test the UI implementations related to: https://github.com/wso2/api-manager/issues/1710

### Description
![image](https://github.com/piyumaldk/apim-apps/assets/28702407/586d5d23-6d6b-4b21-a636-d35c2e748f6c)

2024-01-08 06:42 UTC, piyumaldk requested changes

2024-01-11 00:45 UTC, YasasRangika commented on tests/cypress/integration/publisher/022-gateway-policies/00-gateway-policy.spec.js
> +        cy.get('[data-testid=policy-mapping-delete-confirmation-button]', { timeout: Cypress.config().largeTimeout }).click();
added with https://github.com/wso2/apim-apps/pull/526/commits/98518a7d447f70065b78a706a81e6d39ac4e1b0a.
Thank you!

2024-01-11 00:45 UTC, YasasRangika commented on tests/cypress/integration/publisher/022-gateway-policies/00-gateway-policy.spec.js
> +        cy.wait(2000);
added with https://github.com/wso2/apim-apps/pull/526/commits/98518a7d447f70065b78a706a81e6d39ac4e1b0a.
Thank you!

2024-01-11 00:45 UTC, YasasRangika commented
After fixing latest review comments:
![image](https://github.com/wso2/apim-apps/assets/28702407/e031fb4f-7466-4519-a67f-cd34a4b740b5)

2024-01-11 06:20 UTC, piyumaldk submitted a review, later dismissed

2024-01-14 05:32 UTC, YasasRangika commented
For Reviewers, please note that the newly added test case is passing:
![image](https://github.com/wso2/apim-apps/assets/28702407/4b46ea1a-4e1a-4ab5-9065-82f92c6f34f8)

2024-01-16 03:43 UTC, piyumaldk approved these changes

2024-01-18 10:00 UTC, dulithsenanayake approved these changes

2024-01-19 14:31 UTC, merged