Added UI changes related to Key Manager Usage implementations
wso2/apim-apps pull request #622
Opened 2024-03-22 06:56 UTC by SavinduDimal

### Purpose

- Port https://github.com/wso2-support/apim-apps/pull/157
- Related PRs: https://github.com/wso2/carbon-apimgt/pull/12345
- Related Issues: https://github.com/wso2/api-manager/issues/1943
- Add frontend changes for key manager usages in admin portal
- Add frontend changes for key delete in dev portal

### Description

#### Admin portal changes

- Add new column to view key manager usages.

<img width="1502" alt="Screenshot 2024-03-22 at 12 23 29" src="https://github.com/wso2/apim-apps/assets/55122994/786822b4-6be4-439a-9723-a75a30d9b932">

- Add a pop up to view API usages and Application usages of a key manager
<img width="1503" alt="Screenshot 2024-03-22 at 12 24 24" src="https://github.com/wso2/apim-apps/assets/55122994/c9a5cef2-cf9b-4605-a885-1ec1b49caaf1">

<img width="1503" alt="Screenshot 2024-03-22 at 12 24 40" src="https://github.com/wso2/apim-apps/assets/55122994/4abf3614-36ab-4238-8059-c59e28d56719">

#### Dev portal changes

- Add a button to remove keys
<img width="1503" alt="Screenshot 2024-03-22 at 12 25 43" src="https://github.com/wso2/apim-apps/assets/55122994/879fcdba-ddab-430b-876e-c4e96e72a6f3">

2024-03-22 13:32 UTC, lasanthaS commented on portals/admin/src/main/webapp/source/src/app/data/api.js
> +            return client.apis["Key Manager (Individual)"].get_key_managers__keyManagerId__app_usages(
Put single quotes here

2024-03-22 14:50 UTC, lasanthaS requested changes

2024-03-22 15:54 UTC, SavinduDimal commented on portals/admin/src/main/webapp/source/src/app/components/KeyManagers/ListKeyManagerUsages.jsx
> + * Copyright (c) 2023, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Resolved by https://github.com/wso2/apim-apps/pull/622/commits/04b8ced43a5ae7fea10a867841e7e6e403c77a94

2024-03-22 15:54 UTC, SavinduDimal commented on portals/admin/src/main/webapp/source/src/app/data/api.js
> +            return client.apis["Key Manager (Individual)"].get_key_managers__keyManagerId__api_usages(
Resolved by https://github.com/wso2/apim-apps/pull/622/commits/04b8ced43a5ae7fea10a867841e7e6e403c77a94

2024-03-22 15:55 UTC, SavinduDimal commented on portals/admin/src/main/webapp/source/src/app/data/api.js
> +            return client.apis["Key Manager (Individual)"].get_key_managers__keyManagerId__app_usages(
Resolved by https://github.com/wso2/apim-apps/pull/622/commits/04b8ced43a5ae7fea10a867841e7e6e403c77a94

2024-03-23 01:22 UTC, lasanthaS approved these changes

2024-03-25 06:25 UTC, merged