UI implementation to Support separate client side MTLS for production and sandbox endpoints
wso2/apim-apps pull request #706
Opened 2024-06-12 03:51 UTC by RusJaI

Fixes : https://github.com/wso2/api-manager/issues/2433

2024-06-26 09:27 UTC, lasanthaS approved these changes

2024-07-08 09:15 UTC, lasanthaS requested changes

2024-07-08 09:15 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
> +                                (aliasValidity && !aliasValidity.isValid) ||isAliasIncluded()
add space after `||`

2024-07-08 10:41 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
> +                                (aliasValidity && !aliasValidity.isValid) ||isAliasIncluded()
fixed

2024-07-10 10:11 UTC, lasanthaS submitted a review, later dismissed

2024-07-10 10:24 UTC, Krishanx92 approved these changes

2024-07-10 11:47 UTC, npamudika commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
> +    const [keyType, setkeyType] = useState(API_SECURITY_KEY_TYPE_PRODUCTION);
```suggestion
    const [keyType, setKeyType] = useState(API_SECURITY_KEY_TYPE_PRODUCTION);
```

2024-07-16 12:46 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
> +    const [keyType, setkeyType] = useState(API_SECURITY_KEY_TYPE_PRODUCTION);
fixed

2024-07-16 12:47 UTC, npamudika approved these changes

2024-07-29 03:41 UTC, npamudika approved these changes

2024-07-29 12:44 UTC, merged