Fix UI Alignment issue and Export button issue in View Generated Documentation for Rest APIs
wso2/apim-apps pull request #712
Opened 2024-07-17 09:49 UTC by Jithmi004

## Purpose
This PR fixes the UI alignment issue, and the padding issue of export button in View Generated Documentation for Rest APIs in publisher portal.

Fixes https://github.com/wso2/api-manager/issues/2749

2024-07-17 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/apim-apps?pullRequest=712) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/apim-apps?pullRequest=712) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/apim-apps?pullRequest=712) it.</sub>

2024-07-17 11:22 UTC, lasanthaS requested changes

2024-07-17 11:22 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/elements.css
> +    padding: 8px
Please add a trailing semicolon.

2024-07-18 04:21 UTC, Jithmi004 commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/elements.css
> +    padding: 8px
Done

2024-07-18 04:25 UTC, lasanthaS approved these changes

2024-07-18 04:25 UTC, merged