Add Subscription approval capability to Publisher portal
wso2/apim-apps pull request #719
Opened 2024-07-30 06:17 UTC by shilmyhasan

Add Subscription approval capability to Publisher portal.

2024-07-30 06:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/apim-apps?pullRequest=719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/apim-apps?pullRequest=719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/apim-apps?pullRequest=719) it.</sub>

2024-08-12 06:41 UTC, lasanthaS requested changes

2024-08-12 06:41 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ContentBase.jsx
> + * WSO2 Inc. licenses this file to you under the Apache License,
Change this to WSO2 LLC

2024-08-12 06:41 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ContentBase.jsx
> + * WSO2 Inc. licenses this file to you under the Apache License,
Check other places as well

2024-08-12 06:41 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/InputListBase.jsx
> +import React, { useEffect, useState } from 'react';
Add license header

2024-08-14 12:09 UTC, shilmyhasan commented on portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ContentBase.jsx
> + * WSO2 Inc. licenses this file to you under the Apache License,
Refactored

2024-08-14 12:10 UTC, shilmyhasan commented on portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/InputListBase.jsx
> +import React, { useEffect, useState } from 'react';
Refactored

2024-08-15 09:40 UTC, lasanthaS approved these changes

2024-08-15 09:51 UTC, merged