[Feat]: Provide Sequence as a Backend for APIs
wso2/apim-apps pull request #743
Opened 2024-09-16 04:42 UTC by BLasan

2024-09-16 04:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/apim-apps?pullRequest=743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/apim-apps?pullRequest=743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/apim-apps?pullRequest=743) it.</sub>

2024-09-26 04:57 UTC, RakhithaRR commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
> + * Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Let's change this to the new license text

2024-09-26 04:57 UTC, RakhithaRR commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
> +     * Method to upload the certificate content by calling the rest api.
Shall we fix add the correct method comments

2024-09-26 06:21 UTC, Krishanx92 commented
Can you attached new UI design

2024-09-26 06:50 UTC, Krishanx92 requested changes

2024-09-26 06:50 UTC, Krishanx92 commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
> +                console.log(result);
remove console log

2024-09-26 06:50 UTC, Krishanx92 commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
> +        console.log("Downloading");
remove and check all other places

2024-09-26 06:50 UTC, Krishanx92 commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
> +            console.log('Custom backend uploaded successfully' + resp);
we need messge box not console log

2024-09-26 06:50 UTC, Krishanx92 commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
> +        if(apiObject.gatewayType !== 'wso2/apk' && type === 'HTTP' ) {
formatting

2024-09-26 10:58 UTC, BLasan commented
> Can you attached new UI design

Attached in the description. https://github.com/wso2/apim-apps/pull/743#issue-2527489091

2024-09-26 11:54 UTC, Krishanx92 approved these changes

2024-09-27 05:39 UTC, Krishanx92 approved these changes

2024-09-27 06:24 UTC, RakhithaRR approved these changes

2024-09-27 06:25 UTC, merged