[DRAFT]UI implementation for allowing to have api policy and a common policy with same name and same version
wso2/apim-apps pull request #809
Opened 2024-10-15 11:55 UTC by RusJaI

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +const AttachedPolicyCardShared: FC<AttachedPolicyCardSharedProps> = (props) => {
Shall we revert back to the prop destructuring here?

```suggestion
const AttachedPolicyCardShared: FC<AttachedPolicyCardSharedProps> = ({
     ...
}) => {
```

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +    const policyBackgroundColor = props.drawerOpen
Let's not do these modifications. Check and fix similar places as well.

```suggestion
    const policyColor = Utils.stringToColor(policyObj.displayName);
    const policyBackgroundColor = drawerOpen
```

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +    if ('listOriginatedFromCommonPolicies' in props) {
Can't we specify this as a prop passed down from the parent component instead?

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +        let policyType =   "Common Policy";
Shall we make `Common Policy` and `API Policy` constants?

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +            (<Root>
Can't we remove this `(`?

```suggestion
            <Root>
```

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +const AttachedPolicyListShared: FC<AttachedPolicyListSharedProps> = (props) => {
Shall we destruct the props here?

```suggestion
const AttachedPolicyListShared: FC<AttachedPolicyListSharedProps> = ({
     ...
}) => {
```

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +    if ('listOriginatedFromCommonPolicies' in props) {
Check this as well

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +                                isApiRevision={props.isApiRevision}
Shall we remove the prop from these instances?

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/PoliciesExpansion.tsx
> +const PoliciesExpansionShared: FC<PoliciesExpansionSharedProps> = (props) => {
Destruct props

2025-01-02 11:12 UTC, ashera96 commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/PolicyDropzone.tsx
> +const PolicyDropzoneShared: FC<PolicyDropzoneSharedProps> = (props) => {
Destruct props

2025-01-03 08:47 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +const AttachedPolicyCardShared: FC<AttachedPolicyCardSharedProps> = (props) => {
This change was introduced based on the following considerations:

Data flows through this shared component to both the Global Policy UIs and the API/Common Policy UIs. In the context of Global Policy flows, the concept represented by listOriginatedFromCommonPolicies does not apply, and as a result, this prop is not passed. Furthermore, in the API/Common Policy flows, there are scenarios where listOriginatedFromCommonPolicies may not exist.

Due to the lack of a definitive way to distinguish between a Global Policy page and a standard policy page based solely on the **value** of listOriginatedFromCommonPolicies in the props, destructuring was removed. Instead, a check was introduced to verify **whether the corresponding prop exists among the passed props**, rather than relying on its value.

2025-01-03 08:50 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +    const policyBackgroundColor = props.drawerOpen
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:50 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +    if ('listOriginatedFromCommonPolicies' in props) {
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:51 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +const AttachedPolicyListShared: FC<AttachedPolicyListSharedProps> = (props) => {
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:51 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +    if ('listOriginatedFromCommonPolicies' in props) {
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:51 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyList.tsx
> +                                isApiRevision={props.isApiRevision}
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:51 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/PoliciesExpansion.tsx
> +const PoliciesExpansionShared: FC<PoliciesExpansionSharedProps> = (props) => {
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 08:51 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/PolicyDropzone.tsx
> +const PolicyDropzoneShared: FC<PolicyDropzoneSharedProps> = (props) => {
relates to https://github.com/wso2/apim-apps/pull/809#discussion_r1901575381

2025-01-03 09:54 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +            (<Root>
fixed

2025-01-03 09:54 UTC, RusJaI commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
> +        let policyType =   "Common Policy";
fixed

2025-01-16 08:45 UTC, lasanthaS requested changes

2025-01-16 08:45 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
>              if (showMultiVersionPolicies) {
This can be simplified as follows.

```javascript
// Get the policies depending on the policy display name and version
apiPolicyByPolicyDisplayName = [...apiSpecificPoliciesList
    .reduce((map: Map<string, Policy>, obj: Policy) => 
        map.set((showMultiVersionPolicies ? obj.name + obj.version : obj.name), obj), new Map()).values()];
commonPolicyByPolicyDisplayName = [...commonPoliciesList
    .reduce((map: Map<string, Policy>, obj: Policy) => 
        map.set((showMultiVersionPolicies ? obj.name + obj.version : obj.name), obj), new Map()).values()];
```

2025-01-16 08:45 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
>              if (!isChoreoConnectEnabled) {
This can be simplified as,

```js
let gatewayType = isChoreoConnectEnabled ? 'ChoreoConnect' : 'Synapse';
// Get relevant gateway supported policies
filteredApiPolicyByGatewayTypeList = apiPolicyByPolicyDisplayName.filter(
    (policy: Policy) => policy.supportedGateways.includes(gatewayType));
filteredCommonPolicyByGatewayTypeList = commonPolicyByPolicyDisplayName.filter(
    (policy: Policy) => policy.supportedGateways.includes(gatewayType));
```

2025-01-16 08:45 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
>              if (api.type === "HTTP") {
This can be simplify as,
```js
if (api.type === 'HTTP' || api.type === 'SOAP' || api.type === 'SOAPTOREST') {
    // Get HTTP, SOAP and SOAP to REST supported policies
    filteredApiPoliciesByAPITypeList = filteredApiPolicyByGatewayTypeList.filter(
        (policy: Policy) => policy.supportedApiTypes.includes(api.type));
    filteredCommonPoliciesByAPITypeList = filteredCommonPolicyByGatewayTypeList.filter(
        (policy: Policy) => policy.supportedApiTypes.includes(api.type));
}
```

2025-01-16 08:45 UTC, lasanthaS commented on portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/PoliciesExpansion.tsx
> +                            <props.FlowArrow arrowDirection='left' />
It's better to assign these properties to variables beforehand as follows.

```js
const { FlowArrow, PolicyDropzone, requestFlowPolicyList } = props;
```

2025-01-28 05:35 UTC, RusJaI commented
a new PR https://github.com/wso2/apim-apps/pull/856 was added addressing the review comments. Hence closing this PR

2025-01-28 05:35 UTC, closed without merging